# Generated by Django 4.1.2 on 2022-10-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('genres', models.CharField(max_length=255, verbose_name='Жанры')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('year', models.IntegerField(verbose_name='Год')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер места')),
                ('row', models.CharField(max_length=30, verbose_name='Ряд')),
                ('hall', models.IntegerField(verbose_name='Зал')),
                ('price', models.FloatField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('film_data', models.DateField(auto_now=True, verbose_name='Дата сеанса')),
                ('film_time', models.TimeField(auto_now=True, verbose_name='Время сеанса')),
                ('status', models.CharField(choices=[('R', 'Registered'), ('W', 'In work'), ('C', 'Completed'), ('D', 'Deleted')], max_length=1, verbose_name='Сатус')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.films')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.users')),
            ],
        ),
    ]
