# Generated by Django 4.1.2 on 2022-10-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_seats_number_alter_seats_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='Номер телефона'),
        ),
    ]
